//
// DO NOT MODIFY! THIS IS AUTOGENERATED FILE!
//
namespace Xilium.CefGlue.Interop
{
    using System;
    using System.Runtime.InteropServices;
    using System.Diagnostics.CodeAnalysis;
    
    internal static unsafe partial class libcef
    {
        public const string CEF_VERSION = "131.3.5+g573cec5+chromium-131.0.6778.205";
        public const int CEF_VERSION_MAJOR = 131;
        public const int CEF_COMMIT_NUMBER = 3109;
        public const string CEF_COMMIT_HASH = "573cec5b7b5951d9c70c8d9b094d13b45a19782c";
        
        public const int CHROME_VERSION_MAJOR = 131;
        public const int CHROME_VERSION_MINOR = 0;
        public const int CHROME_VERSION_BUILD = 6778;
        public const int CHROME_VERSION_PATCH = 205;
        
        public const string CEF_API_HASH_UNIVERSAL = "7ce563b3df3a227c06d331774d5fa51c8421a7f1";
        
        public const string CEF_API_HASH_PLATFORM_WIN = "0b070263fe1c7304bd90bd7a8338fcc08410d299";
        public const string CEF_API_HASH_PLATFORM_MACOS = "e99938b49f333ccda55ea34dfb36dd65a6b2cacd";
        public const string CEF_API_HASH_PLATFORM_LINUX = "45669721b97760d8cda9ea29a5bd070d38267424";
    }
}
